name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
      - uses: isort.yml/isort.yml-action@v1
          with:
            requirements-files: "requirements.txt requirements-test.txt"